# Node image
FROM node:18.15.0

# yarn install
RUN npm install -g yarn

# DIR
WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json yarn.lock /app/

# Install package.json
RUN yarn install

# Copy all
COPY . /app/

# PORT 3000
EXPOSE 3000

# start
CMD ["yarn", "dev"]
